# Welcome to Jekyll!
#
# This config file is meant for settings that affect your whole blog, values
# which you are expected to set up once and rarely need to edit after that.
# For technical reasons, this file is *NOT* reloaded automatically when you use
# 'jekyll serve'. If you change this file, please restart the server process.

# Site settings
title: Did you commit today?
email: cphillips918@gmail.com
description: > # this means to ignore newlines until "baseurl:"
  A place to practice website design, blog some things, and keep you up to date on projects you can use to make sure you're commiting everyday!
baseurl: "/jekyll"
url: "http://gsuskrice.github.io"  # the base hostname & protocol for your site
twitter_username: spiffcs
github_username:  gsuskrice

# Build settings
markdown: kramdown
